version: "3.8"
services:
  backend1:
    build: ./social_network/backend1
    image: nastyatkach/social_network-main_backend1
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    container_name: twitter-backend1
  fronend1:
    build: ./social_network/fronend1
    image: nastyatkach/social_network-main_fronend1
    restart: always
    ports:
      - "3000:3000"
    container_name: twitter-fronend1
  mongo:
    image: mongo
    command: mongod --port 27017
    restart: always
    ports:
      - "27017:27017"
    container_name: mongo